name: test and build Docker-Devops

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build, Test, and Push Docker Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Test App
        run: |
          mvn clean package -B

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        env:
          DOCKER_REPO: kamhassan/docker-devops
          BASE_TAG: v1-data-shakey
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          IMAGE_TAG="${BASE_TAG}-${SHORT_SHA}"

          echo "Building Docker image with tag: $DOCKER_REPO:$IMAGE_TAG"
          docker build -t $DOCKER_REPO:$IMAGE_TAG .

          echo "Pushing image to Docker Hub..."
          docker push $DOCKER_REPO:$IMAGE_TAG

          echo "::notice::Docker image pushed: $DOCKER_REPO:$IMAGE_TAG"
