name: test and build Docker-Devops

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build, Test, and Push Docker Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
        
      - name: Install Maven (for local act only)
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
        
      - name: Unit tests
        run: mvn -B test --file pom.xml
        
      - name: Build the app
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t kamhassan/spring-boot-docker:v1.0 .

      - name: Push Docker image
        run: docker push kamhassan/spring-boot-docker:v1.0
